apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: gangadhargottiveeti/sensor-data-producer-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: MONGO_URI
              value: mongodb://gangadhar:password@mongodb:27017/iot-platform?authSource=admin